// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: services/connectors/v1/responses.proto

package connectors

import (
	_ "google.golang.org/genproto/googleapis/services/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CatalogConnector_AuthType int32

const (
	CatalogConnector_OAUTH2  CatalogConnector_AuthType = 0
	CatalogConnector_API_KEY CatalogConnector_AuthType = 1
)

// Enum value maps for CatalogConnector_AuthType.
var (
	CatalogConnector_AuthType_name = map[int32]string{
		0: "OAUTH2",
		1: "API_KEY",
	}
	CatalogConnector_AuthType_value = map[string]int32{
		"OAUTH2":  0,
		"API_KEY": 1,
	}
)

func (x CatalogConnector_AuthType) Enum() *CatalogConnector_AuthType {
	p := new(CatalogConnector_AuthType)
	*p = x
	return p
}

func (x CatalogConnector_AuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CatalogConnector_AuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_services_connectors_v1_responses_proto_enumTypes[0].Descriptor()
}

func (CatalogConnector_AuthType) Type() protoreflect.EnumType {
	return &file_services_connectors_v1_responses_proto_enumTypes[0]
}

func (x CatalogConnector_AuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CatalogConnector_AuthType.Descriptor instead.
func (CatalogConnector_AuthType) EnumDescriptor() ([]byte, []int) {
	return file_services_connectors_v1_responses_proto_rawDescGZIP(), []int{0, 0}
}

type CatalogConnector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IconUrl  string `protobuf:"bytes,3,opt,name=iconUrl,proto3" json:"iconUrl,omitempty"`
	AuthType string `protobuf:"bytes,4,opt,name=authType,proto3" json:"authType,omitempty"`
	AuthUrl  string `protobuf:"bytes,5,opt,name=authUrl,proto3" json:"authUrl,omitempty"`
}

func (x *CatalogConnector) Reset() {
	*x = CatalogConnector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_connectors_v1_responses_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CatalogConnector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogConnector) ProtoMessage() {}

func (x *CatalogConnector) ProtoReflect() protoreflect.Message {
	mi := &file_services_connectors_v1_responses_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogConnector.ProtoReflect.Descriptor instead.
func (*CatalogConnector) Descriptor() ([]byte, []int) {
	return file_services_connectors_v1_responses_proto_rawDescGZIP(), []int{0}
}

func (x *CatalogConnector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CatalogConnector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CatalogConnector) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *CatalogConnector) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *CatalogConnector) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

type CatalogConnectorList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Connectors []*CatalogConnector `protobuf:"bytes,2,rep,name=connectors,proto3" json:"connectors,omitempty"`
}

func (x *CatalogConnectorList) Reset() {
	*x = CatalogConnectorList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_connectors_v1_responses_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CatalogConnectorList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogConnectorList) ProtoMessage() {}

func (x *CatalogConnectorList) ProtoReflect() protoreflect.Message {
	mi := &file_services_connectors_v1_responses_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogConnectorList.ProtoReflect.Descriptor instead.
func (*CatalogConnectorList) Descriptor() ([]byte, []int) {
	return file_services_connectors_v1_responses_proto_rawDescGZIP(), []int{1}
}

func (x *CatalogConnectorList) GetConnectors() []*CatalogConnector {
	if x != nil {
		return x.Connectors
	}
	return nil
}

type WorkspaceConnectorList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Connectors []*WorkspaceConnector `protobuf:"bytes,1,rep,name=connectors,proto3" json:"connectors,omitempty"`
}

func (x *WorkspaceConnectorList) Reset() {
	*x = WorkspaceConnectorList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_connectors_v1_responses_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkspaceConnectorList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceConnectorList) ProtoMessage() {}

func (x *WorkspaceConnectorList) ProtoReflect() protoreflect.Message {
	mi := &file_services_connectors_v1_responses_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceConnectorList.ProtoReflect.Descriptor instead.
func (*WorkspaceConnectorList) Descriptor() ([]byte, []int) {
	return file_services_connectors_v1_responses_proto_rawDescGZIP(), []int{2}
}

func (x *WorkspaceConnectorList) GetConnectors() []*WorkspaceConnector {
	if x != nil {
		return x.Connectors
	}
	return nil
}

type WorkspaceConnector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId string                 `protobuf:"bytes,2,opt,name=workspaceId,proto3" json:"workspaceId,omitempty"`
	Name        string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status      string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ExpiresIn   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiresIn,proto3" json:"expiresIn,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *WorkspaceConnector) Reset() {
	*x = WorkspaceConnector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_connectors_v1_responses_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkspaceConnector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceConnector) ProtoMessage() {}

func (x *WorkspaceConnector) ProtoReflect() protoreflect.Message {
	mi := &file_services_connectors_v1_responses_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceConnector.ProtoReflect.Descriptor instead.
func (*WorkspaceConnector) Descriptor() ([]byte, []int) {
	return file_services_connectors_v1_responses_proto_rawDescGZIP(), []int{3}
}

func (x *WorkspaceConnector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkspaceConnector) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *WorkspaceConnector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkspaceConnector) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkspaceConnector) GetExpiresIn() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresIn
	}
	return nil
}

func (x *WorkspaceConnector) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkspaceConnector) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_services_connectors_v1_responses_proto protoreflect.FileDescriptor

var file_services_connectors_v1_responses_proto_rawDesc = []byte{
	0x0a, 0x26, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab, 0x01, 0x0a, 0x10,
	0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x75,
	0x74, 0x68, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x75, 0x74,
	0x68, 0x55, 0x72, 0x6c, 0x22, 0x23, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x41, 0x55, 0x54, 0x48, 0x32, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x41, 0x50, 0x49, 0x5f, 0x4b, 0x45, 0x59, 0x10, 0x01, 0x22, 0x4c, 0x0a, 0x14, 0x43, 0x61, 0x74,
	0x61, 0x6c, 0x6f, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x34, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x61, 0x6c,
	0x6f, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0a, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x50, 0x0a, 0x16, 0x57, 0x6f, 0x72, 0x6b, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x36, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0a, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0xa0, 0x02, 0x0a, 0x12, 0x57, 0x6f,
	0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x38,
	0x0a, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x49, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x49, 0x6e, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x42, 0x5a, 0x40,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x75, 0x74, 0x6c, 0x65,
	0x72, 0x68, 0x71, 0x2f, 0x62, 0x75, 0x74, 0x6c, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_connectors_v1_responses_proto_rawDescOnce sync.Once
	file_services_connectors_v1_responses_proto_rawDescData = file_services_connectors_v1_responses_proto_rawDesc
)

func file_services_connectors_v1_responses_proto_rawDescGZIP() []byte {
	file_services_connectors_v1_responses_proto_rawDescOnce.Do(func() {
		file_services_connectors_v1_responses_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_connectors_v1_responses_proto_rawDescData)
	})
	return file_services_connectors_v1_responses_proto_rawDescData
}

var file_services_connectors_v1_responses_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_connectors_v1_responses_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_connectors_v1_responses_proto_goTypes = []interface{}{
	(CatalogConnector_AuthType)(0), // 0: v1.CatalogConnector.AuthType
	(*CatalogConnector)(nil),       // 1: v1.CatalogConnector
	(*CatalogConnectorList)(nil),   // 2: v1.CatalogConnectorList
	(*WorkspaceConnectorList)(nil), // 3: v1.WorkspaceConnectorList
	(*WorkspaceConnector)(nil),     // 4: v1.WorkspaceConnector
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_services_connectors_v1_responses_proto_depIdxs = []int32{
	1, // 0: v1.CatalogConnectorList.connectors:type_name -> v1.CatalogConnector
	4, // 1: v1.WorkspaceConnectorList.connectors:type_name -> v1.WorkspaceConnector
	5, // 2: v1.WorkspaceConnector.expiresIn:type_name -> google.protobuf.Timestamp
	5, // 3: v1.WorkspaceConnector.createdAt:type_name -> google.protobuf.Timestamp
	5, // 4: v1.WorkspaceConnector.updatedAt:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_services_connectors_v1_responses_proto_init() }
func file_services_connectors_v1_responses_proto_init() {
	if File_services_connectors_v1_responses_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_connectors_v1_responses_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CatalogConnector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_connectors_v1_responses_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CatalogConnectorList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_connectors_v1_responses_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkspaceConnectorList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_connectors_v1_responses_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkspaceConnector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_connectors_v1_responses_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_connectors_v1_responses_proto_goTypes,
		DependencyIndexes: file_services_connectors_v1_responses_proto_depIdxs,
		EnumInfos:         file_services_connectors_v1_responses_proto_enumTypes,
		MessageInfos:      file_services_connectors_v1_responses_proto_msgTypes,
	}.Build()
	File_services_connectors_v1_responses_proto = out.File
	file_services_connectors_v1_responses_proto_rawDesc = nil
	file_services_connectors_v1_responses_proto_goTypes = nil
	file_services_connectors_v1_responses_proto_depIdxs = nil
}
