default: &default
  environment: dev

logger: &logger
  <<: *default
  disableCaller: true
  disableStacktrace: false
  encoding: json
  level: debug

jaeger: &jaeger
  host: jaeger:6831
  logSpans: false


# Config for Postgres
postgres: &postgres
  <<: *default
  host: postgres
  port: 5432
  defaultName: postgres
  name: postgres
  user: postgres
  password: password

# Config for redis
redis: &redis
  host: redis
  port: 6379
  db: 0

# Config for Auth service
auth:
  <<: *default
  port: 3001
  jaeger:
    <<: *jaeger
    serviceName: Auth_GRPC
  jwtSecret: super-jwt-secret
  postgres:
    <<: *postgres
    name: auth
  redis:
    <<: *redis
  logger: 
    <<: *logger
  googleOAuth:
    

# Config for User Profile service
workspace:
  <<: *default
  port: 3002
  authServiceAddr: "auth:3001"
  postgres:
    <<: *postgres
    name: workspace
  logger: 
    <<: *logger
  jaeger:
    <<: *jaeger
    serviceName: Workspace_GRPC

# Config for User Profile service
gateway:
  <<: *default
  port: 8080
  authServiceAddr: "auth:3001"
  workspaceServiceAddr: "workspace:3002"
  dashboardOriginUrl: "http://localhost:3000"
  logger:
    <<: *logger
  jaeger:
    <<: *jaeger
    serviceName: Gateway_REST