# .air.conf
# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "." 
tmp_dir = "/tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "time go build -i -o /tmp/workspace/main github.com/matthieuberger/butler/cmd/workspace"
# Binary file yields from `cmd`.
bin = "/tmp/workspace/main"
# Customize binary.
full_bin = "/tmp/workspace/main start --dir ./config/services"
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html"]

# Watch these directories if you specified.
include_dir = ["internal"]

# Exclude files.
exclude_file = []

# Exclude unchanged files.
exclude_unchanged = true

# This log file places in your tmp_dir.
log = "workspace_air.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = true
# Delay after sending Interrupt signal
kill_delay = 0 # ms

[log]
# Show log time
time = true

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Don't delete tmp directory on exit because it's needed for docker volumes
clean_on_exit = true
