version: "3.6"

services:
  jaeger:
    container_name: jaeger_container
    image: jaegertracing/all-in-one:1.27
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - dev_net

  postgres:
    image: public.ecr.aws/c1s5x5y2/butlerhq/postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=user_db,connector_db
    networks:
      - dev_net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
       - pgadmin:/root/.pgadmin
    networks:
      - dev_net

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - dev_net

  victorinox:
    working_dir: /butler
    build:
      context: ../..
      target: victorinox
    volumes:
      - ../../:/butler
    depends_on:
      - postgres
    command: >
      /butler-victorinox migrate up --service users --config config/tools/victorinox_config.yaml &&
      /butler-victorinox migrate up --service octopus --config config/tools/victorinox_config.yaml
    networks:
      - dev_net

  users:
    image: cosmtrek/air
    working_dir: /butler
    volumes:
      - ../..:/butler:delegated
      - ../../config/services/users:/config
    entrypoint: [ "air", "-c", "/config/air.toml" ]
    env_file:
      - ../../.env
    ports:
      - 3001:3001
    depends_on:
      - postgres
    networks:
      - dev_net

  octopus:
    image: cosmtrek/air
    working_dir: /butler
    env_file:
      - ../../.env
    ports:
      - 3002:3002
    volumes:
      - ../..:/butler:delegated
      - ../../config/services/octopus:/config
    entrypoint: [ "air", "-c", "/config/air.toml" ]
    depends_on:
      - postgres
    networks:
      - dev_net

  gateway:
    image: cosmtrek/air
    working_dir: /butler
    volumes:
      - ../..:/butler:delegated
      - ../../config/services/gateway:/config
    entrypoint: [ "air", "-c", "/config/air.toml" ]
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - dev_net

  webapp:
    build:
      context: ../../webapp
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ../../webapp:/app
    environment:
      - BUILD_TARGET=local
      - APP_VERSION=local
      - API_BASE_URL=http://localhost:8080
      - APP_BASE_URL=http://localhost:3000
    depends_on:
      - gateway
    networks:
      - dev_net

volumes:
  postgres:
  redis:
  pgadmin:

networks:
  dev_net:
    driver: bridge
