version: "3.6"

services:
  jaeger:
    container_name: jaeger_container
    image: jaegertracing/all-in-one:1.27
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - dev_net

  postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    networks:
      - dev_net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
       - pgadmin:/root/.pgadmin
    networks:
      - dev_net

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - dev_net

  victorinox:
    build:
      context: ../..
      target: victorinox
    volumes:
      - ../../config:/config
    depends_on:
      - postgres
    command: >
      /butler-victorinox migrate up --dir /config
    networks:
      - dev_net
#  auth:
#    build:
#      context: ../..
#      dockerfile: build/auth/Dockerfile.dev
#    ports:
#      - 3001:3001
#    volumes:
#      - ../..:/go/src/butler:delegated
#    networks:
#      - dev_net
#
#  workspace:
#    build:
#      context: ../..
#      dockerfile: build/workspace/Dockerfile.dev
#    ports:
#      - 3002:3002
#    volumes:
#      - ../..:/go/src/butler:delegated
#    networks:
#      - dev_net
#
#  gateway:
#    build:
#      context: ../..
#      dockerfile: build/gateway/Dockerfile.dev
#    ports:
#      - 8080:8080
#    volumes:
#      - ../..:/go/src/butler:delegated
#    networks:
#      - dev_net

volumes:
  postgres:
  redis:
  pgadmin:

networks:
  dev_net:
    driver: bridge
