apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-volume
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/component: database
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/redis"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pv-claim
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/component: database
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: {{ .Release.Name}}
      app.kubernetes.io/component: database
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/instance: {{ .Release.Name}}
        app.kubernetes.io/component: database
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
    spec:
      containers:
        - name: master
          image: redis:alpine
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/component: database
    app.kubernetes.io/version: {{ .Chart.AppVersion }}