environment: dev
logger:
  disableCaller: true
  disableStacktrace: false
  encoding: json
  level: debug
jaeger:
  host: jaeger:6831
  logSpans: true
  serviceName: User_GRPC
postgres:
  host: postgres
  port: 5432
  name: connector_db
  user: postgres
  password: password
connectors:
  google:
    clientID: clientID
    clientSecret: clientSecret
    redirectURL: redirectUrl
  linkedin:
    clientID: clientID
    clientSecret: clientSecret
    redirectURL: redirectUrl
port: 3002