package linkedin_ads

const LINKEDIN_ADS_STREAMS_CATALOG = `{
  "streams":[
    {
      "stream":{
        "name":"accounts",
        "jsonSchema":{
          "type":[
            "null",
            "object"
          ],
          "properties":{
            "test":{
              "type":[
                "null",
                "boolean"
              ]
            },
            "notifiedOnCreativeRejection":{
              "type":[
                "null",
                "boolean"
              ]
            },
            "notifiedOnEndOfCampaign":{
              "type":[
                "null",
                "boolean"
              ]
            },
            "servingStatuses":{
              "type":[
                "null",
                "array"
              ],
              "items":{
                "type":[
                  "null",
                  "string"
                ]
              }
            },
            "notifiedOnCampaignOptimization":{
              "type":[
                "null",
                "boolean"
              ]
            },
            "type":{
              "type":[
                "null",
                "string"
              ]
            },
            "version":{
              "type":[
                "null",
                "object"
              ],
              "properties":{
                "versionTag":{
                  "type":[
                    "null",
                    "string"
                  ]
                }
              }
            },
            "reference":{
              "type":[
                "null",
                "string"
              ]
            },
            "notifiedOnCreativeApproval":{
              "type":[
                "null",
                "boolean"
              ]
            },
            "created":{
              "type":[
                "null",
                "string"
              ],
              "format":"date-time"
            },
            "lastModified":{
              "type":[
                "null",
                "string"
              ],
              "format":"date-time"
            },
            "name":{
              "type":[
                "null",
                "string"
              ]
            },
            "currency":{
              "type":[
                "null",
                "string"
              ]
            },
            "id":{
              "type":[
                "null",
                "integer"
              ]
            },
            "status":{
              "type":[
                "null",
                "string"
              ]
            }
          }
        },
        "supportedSyncModes":[
          "full_refresh"
        ],
        "sourceDefinedCursor":null,
        "defaultCursorField":[
          
        ],
        "sourceDefinedPrimaryKey":[
          [
            "id"
          ]
        ],
        "namespace":null
      },
      "config":{
        "syncMode":"full_refresh",
        "cursorField":[
          
        ],
        "destinationSyncMode":"append",
        "primaryKey":[
          [
            "id"
          ]
        ],
        "aliasName":"accounts",
        "selected":true
      }
    },
    {
      "stream":{
        "name":"account_users",
        "jsonSchema":{
          "type":[
            "null",
            "object"
          ],
          "properties":{
            "account":{
              "type":[
                "null",
                "string"
              ]
            },
            "created":{
              "type":[
                "null",
                "string"
              ],
              "format":"date-time"
            },
            "lastModified":{
              "type":[
                "null",
                "string"
              ],
              "format":"date-time"
            },
            "role":{
              "type":[
                "null",
                "string"
              ]
            },
            "user":{
              "type":[
                "null",
                "string"
              ]
            }
          }
        },
        "supportedSyncModes":[
          "full_refresh",
          "incremental"
        ],
        "sourceDefinedCursor":true,
        "defaultCursorField":[
          "lastModified"
        ],
        "sourceDefinedPrimaryKey":[
          [
            "account"
          ]
        ],
        "namespace":null
      },
      "config":{
        "syncMode":"full_refresh",
        "cursorField":[
          "lastModified"
        ],
        "destinationSyncMode":"append",
        "primaryKey":[
          [
            "account"
          ]
        ],
        "aliasName":"account_users",
        "selected":true
      }
    },
    {
      "stream":{
        "name":"ad_campaign_analytics",
        "jsonSchema":{
          "type":[
            "null",
            "object"
          ],
          "properties":{
            "actionClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "adUnitClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "clicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "comments":{
              "type":[
                "null",
                "number"
              ]
            },
            "companyPageClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "conversionValueInLocalCurrency":{
              "type":[
                "null",
                "string"
              ]
            },
            "costInLocalCurrency":{
              "type":[
                "null",
                "string"
              ]
            },
            "costInUsd":{
              "type":[
                "null",
                "string"
              ]
            },
            "start_date":{
              "type":[
                "null",
                "string"
              ],
              "format":"date"
            },
            "end_date":{
              "type":[
                "null",
                "string"
              ],
              "format":"date"
            },
            "externalWebsiteConversions":{
              "type":[
                "null",
                "number"
              ]
            },
            "externalWebsitePostClickConversions":{
              "type":[
                "null",
                "number"
              ]
            },
            "externalWebsitePostViewConversions":{
              "type":[
                "null",
                "number"
              ]
            },
            "follows":{
              "type":[
                "null",
                "number"
              ]
            },
            "fullScreenPlays":{
              "type":[
                "null",
                "number"
              ]
            },
            "impressions":{
              "type":[
                "null",
                "number"
              ]
            },
            "landingPageClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "leadGenerationMailContactInfoShares":{
              "type":[
                "null",
                "number"
              ]
            },
            "leadGenerationMailInterestedClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "likes":{
              "type":[
                "null",
                "number"
              ]
            },
            "oneClickLeadFormOpens":{
              "type":[
                "null",
                "number"
              ]
            },
            "oneClickLeads":{
              "type":[
                "null",
                "number"
              ]
            },
            "opens":{
              "type":[
                "null",
                "number"
              ]
            },
            "otherEngagements":{
              "type":[
                "null",
                "number"
              ]
            },
            "pivot":{
              "type":[
                "null",
                "string"
              ]
            },
            "pivotValue":{
              "type":[
                "null",
                "string"
              ]
            },
            "pivotValues":{
              "type":[
                "null",
                "array"
              ],
              "items":{
                "type":[
                  "null",
                  "string"
                ]
              }
            },
            "reactions":{
              "type":[
                "null",
                "number"
              ]
            },
            "sends":{
              "type":[
                "null",
                "number"
              ]
            },
            "shares":{
              "type":[
                "null",
                "number"
              ]
            },
            "textUrlClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "totalEngagements":{
              "type":[
                "null",
                "number"
              ]
            },
            "videoCompletions":{
              "type":[
                "null",
                "number"
              ]
            },
            "videoFirstQuartileCompletions":{
              "type":[
                "null",
                "number"
              ]
            },
            "videoMidpointCompletions":{
              "type":[
                "null",
                "number"
              ]
            },
            "videoStarts":{
              "type":[
                "null",
                "number"
              ]
            },
            "videoThirdQuartileCompletions":{
              "type":[
                "null",
                "number"
              ]
            },
            "videoViews":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralComments":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralCommentLikes":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralCompanyPageClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralExternalWebsiteConversions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralExternalWebsitePostClickConversions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralExternalWebsitePostViewConversions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralFollows":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralFullScreenPlays":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralImpressions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralLandingPageClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralLikes":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralOneClickLeadFormOpens":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralOneClickLeads":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralOtherEngagements":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralReactions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralShares":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralTotalEngagements":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralVideoCompletions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralVideoFirstQuartileCompletions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralVideoMidpointCompletions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralVideoStarts":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralVideoThirdQuartileCompletions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralVideoViews":{
              "type":[
                "null",
                "number"
              ]
            }
          }
        },
        "supportedSyncModes":[
          "full_refresh",
          "incremental"
        ],
        "sourceDefinedCursor":true,
        "defaultCursorField":[
          "end_date"
        ],
        "sourceDefinedPrimaryKey":[
          [
            "pivotValue"
          ],
          [
            "end_date"
          ]
        ],
        "namespace":null
      },
      "config":{
        "syncMode":"full_refresh",
        "cursorField":[
          "end_date"
        ],
        "destinationSyncMode":"append",
        "primaryKey":[
          [
            "pivotValue"
          ],
          [
            "end_date"
          ]
        ],
        "aliasName":"ad_campaign_analytics",
        "selected":true
      }
    },
    {
      "stream":{
        "name":"ad_creative_analytics",
        "jsonSchema":{
          "type":[
            "null",
            "object"
          ],
          "properties":{
            "actionClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "adUnitClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "clicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "comments":{
              "type":[
                "null",
                "number"
              ]
            },
            "companyPageClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "conversionValueInLocalCurrency":{
              "type":[
                "null",
                "string"
              ]
            },
            "costInLocalCurrency":{
              "type":[
                "null",
                "string"
              ]
            },
            "costInUsd":{
              "type":[
                "null",
                "string"
              ]
            },
            "start_date":{
              "type":[
                "null",
                "string"
              ],
              "format":"date"
            },
            "end_date":{
              "type":[
                "null",
                "string"
              ],
              "format":"date"
            },
            "externalWebsiteConversions":{
              "type":[
                "null",
                "number"
              ]
            },
            "externalWebsitePostClickConversions":{
              "type":[
                "null",
                "number"
              ]
            },
            "externalWebsitePostViewConversions":{
              "type":[
                "null",
                "number"
              ]
            },
            "follows":{
              "type":[
                "null",
                "number"
              ]
            },
            "fullScreenPlays":{
              "type":[
                "null",
                "number"
              ]
            },
            "impressions":{
              "type":[
                "null",
                "number"
              ]
            },
            "landingPageClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "leadGenerationMailContactInfoShares":{
              "type":[
                "null",
                "number"
              ]
            },
            "leadGenerationMailInterestedClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "likes":{
              "type":[
                "null",
                "number"
              ]
            },
            "oneClickLeadFormOpens":{
              "type":[
                "null",
                "number"
              ]
            },
            "oneClickLeads":{
              "type":[
                "null",
                "number"
              ]
            },
            "opens":{
              "type":[
                "null",
                "number"
              ]
            },
            "otherEngagements":{
              "type":[
                "null",
                "number"
              ]
            },
            "pivot":{
              "type":[
                "null",
                "string"
              ]
            },
            "pivotValue":{
              "type":[
                "null",
                "string"
              ]
            },
            "pivotValues":{
              "type":[
                "null",
                "array"
              ],
              "items":{
                "type":[
                  "null",
                  "string"
                ]
              }
            },
            "reactions":{
              "type":[
                "null",
                "number"
              ]
            },
            "sends":{
              "type":[
                "null",
                "number"
              ]
            },
            "shares":{
              "type":[
                "null",
                "number"
              ]
            },
            "textUrlClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "totalEngagements":{
              "type":[
                "null",
                "number"
              ]
            },
            "videoCompletions":{
              "type":[
                "null",
                "number"
              ]
            },
            "videoFirstQuartileCompletions":{
              "type":[
                "null",
                "number"
              ]
            },
            "videoMidpointCompletions":{
              "type":[
                "null",
                "number"
              ]
            },
            "videoStarts":{
              "type":[
                "null",
                "number"
              ]
            },
            "videoThirdQuartileCompletions":{
              "type":[
                "null",
                "number"
              ]
            },
            "videoViews":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralComments":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralCommentLikes":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralCompanyPageClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralExternalWebsiteConversions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralExternalWebsitePostClickConversions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralExternalWebsitePostViewConversions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralFollows":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralFullScreenPlays":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralImpressions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralLandingPageClicks":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralLikes":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralOneClickLeadFormOpens":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralOneClickLeads":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralOtherEngagements":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralReactions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralShares":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralTotalEngagements":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralVideoCompletions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralVideoFirstQuartileCompletions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralVideoMidpointCompletions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralVideoStarts":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralVideoThirdQuartileCompletions":{
              "type":[
                "null",
                "number"
              ]
            },
            "viralVideoViews":{
              "type":[
                "null",
                "number"
              ]
            }
          }
        },
        "supportedSyncModes":[
          "full_refresh",
          "incremental"
        ],
        "sourceDefinedCursor":true,
        "defaultCursorField":[
          "end_date"
        ],
        "sourceDefinedPrimaryKey":[
          [
            "pivotValue"
          ],
          [
            "end_date"
          ]
        ],
        "namespace":null
      },
      "config":{
        "syncMode":"full_refresh",
        "cursorField":[
          "end_date"
        ],
        "destinationSyncMode":"append",
        "primaryKey":[
          [
            "pivotValue"
          ],
          [
            "end_date"
          ]
        ],
        "aliasName":"ad_creative_analytics",
        "selected":true
      }
    },
    {
      "stream":{
        "name":"ad_direct_sponsored_contents",
        "jsonSchema":{
          "type":[
            "null",
            "object"
          ],
          "properties":{
            "owner":{
              "type":[
                "null",
                "string"
              ]
            },
            "contentReference":{
              "type":[
                "null",
                "string"
              ]
            },
            "name":{
              "type":[
                "null",
                "string"
              ]
            },
            "type":{
              "type":[
                "null",
                "string"
              ]
            },
            "account":{
              "type":[
                "null",
                "string"
              ]
            },
            "status":{
              "type":[
                "null",
                "string"
              ]
            },
            "created":{
              "type":[
                "null",
                "string"
              ],
              "format":"date-time"
            },
            "lastModified":{
              "type":[
                "null",
                "string"
              ],
              "format":"date-time"
            }
          }
        },
        "supportedSyncModes":[
          "full_refresh",
          "incremental"
        ],
        "sourceDefinedCursor":true,
        "defaultCursorField":[
          "lastModified"
        ],
        "sourceDefinedPrimaryKey":[
          [
            "account"
          ]
        ],
        "namespace":null
      },
      "config":{
        "syncMode":"full_refresh",
        "cursorField":[
          "lastModified"
        ],
        "destinationSyncMode":"append",
        "primaryKey":[
          [
            "account"
          ]
        ],
        "aliasName":"ad_direct_sponsored_contents",
        "selected":true
      }
    },
    {
      "stream":{
        "name":"campaign_groups",
        "jsonSchema":{
          "type":[
            "null",
            "object"
          ],
          "properties":{
            "runSchedule":{
              "type":[
                "null",
                "object"
              ],
              "properties":{
                "start":{
                  "type":[
                    "null",
                    "integer"
                  ]
                },
                "end":{
                  "type":[
                    "null",
                    "integer"
                  ]
                }
              }
            },
            "created":{
              "type":[
                "null",
                "string"
              ],
              "format":"date-time"
            },
            "lastModified":{
              "type":[
                "null",
                "string"
              ],
              "format":"date-time"
            },
            "name":{
              "type":[
                "null",
                "string"
              ]
            },
            "test":{
              "type":[
                "null",
                "boolean"
              ]
            },
            "servingStatuses":{
              "type":[
                "null",
                "array"
              ],
              "items":{
                "type":[
                  "null",
                  "string"
                ]
              }
            },
            "allowedCampaignTypes":{
              "type":[
                "null",
                "array"
              ],
              "items":{
                "type":[
                  "null",
                  "string"
                ]
              }
            },
            "backfilled":{
              "type":[
                "null",
                "boolean"
              ]
            },
            "id":{
              "type":[
                "null",
                "integer"
              ]
            },
            "account":{
              "type":[
                "null",
                "string"
              ]
            },
            "status":{
              "type":[
                "null",
                "string"
              ]
            }
          }
        },
        "supportedSyncModes":[
          "full_refresh",
          "incremental"
        ],
        "sourceDefinedCursor":true,
        "defaultCursorField":[
          "lastModified"
        ],
        "sourceDefinedPrimaryKey":[
          [
            "id"
          ]
        ],
        "namespace":null
      },
      "config":{
        "syncMode":"full_refresh",
        "cursorField":[
          "lastModified"
        ],
        "destinationSyncMode":"append",
        "primaryKey":[
          [
            "id"
          ]
        ],
        "aliasName":"campaign_groups",
        "selected":true
      }
    },
    {
      "stream":{
        "name":"campaigns",
        "jsonSchema":{
          "type":[
            "null",
            "object"
          ],
          "properties":{
            "targetingCriteria":{
              "type":[
                "null",
                "object"
              ],
              "properties":{
                "include":{
                  "type":[
                    "null",
                    "object"
                  ],
                  "properties":{
                    "and":{
                      "type":[
                        "null",
                        "array"
                      ],
                      "items":{
                        "type":[
                          "null",
                          "object"
                        ],
                        "properties":{
                          "type":{
                            "type":[
                              "null",
                              "string"
                            ]
                          },
                          "values":{
                            "type":[
                              "null",
                              "array"
                            ],
                            "items":{
                              "type":[
                                "null",
                                "string"
                              ]
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "exclude":{
                  "type":[
                    "null",
                    "object"
                  ],
                  "properties":{
                    "or":{
                      "type":[
                        "null",
                        "array"
                      ],
                      "items":{
                        "type":[
                          "null",
                          "object"
                        ],
                        "properties":{
                          "type":{
                            "type":[
                              "null",
                              "string"
                            ]
                          },
                          "values":{
                            "type":[
                              "null",
                              "array"
                            ],
                            "items":{
                              "type":[
                                "null",
                                "string"
                              ]
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            },
            "servingStatuses":{
              "type":[
                "null",
                "array"
              ],
              "items":{
                "type":[
                  "null",
                  "string"
                ]
              }
            },
            "type":{
              "type":[
                "null",
                "string"
              ]
            },
            "locale":{
              "type":[
                "null",
                "object"
              ],
              "properties":{
                "country":{
                  "type":[
                    "null",
                    "string"
                  ]
                },
                "language":{
                  "type":[
                    "null",
                    "string"
                  ]
                }
              }
            },
            "version":{
              "type":[
                "null",
                "object"
              ],
              "properties":{
                "versionTag":{
                  "type":[
                    "null",
                    "string"
                  ]
                }
              }
            },
            "associatedEntity":{
              "type":[
                "null",
                "string"
              ]
            },
            "runSchedule":{
              "type":[
                "null",
                "object"
              ],
              "properties":{
                "start":{
                  "type":[
                    "null",
                    "integer"
                  ]
                },
                "end":{
                  "type":[
                    "null",
                    "integer"
                  ]
                }
              }
            },
            "optimizationTargetType":{
              "type":[
                "null",
                "string"
              ]
            },
            "created":{
              "type":[
                "null",
                "string"
              ],
              "format":"date-time"
            },
            "lastModified":{
              "type":[
                "null",
                "string"
              ],
              "format":"date-time"
            },
            "campaignGroup":{
              "type":[
                "null",
                "string"
              ]
            },
            "dailyBudget":{
              "type":[
                "null",
                "object"
              ],
              "properties":{
                "amount":{
                  "type":[
                    "null",
                    "string"
                  ]
                },
                "currencyCode":{
                  "type":[
                    "null",
                    "string"
                  ]
                }
              }
            },
            "unitCost":{
              "type":[
                "null",
                "object"
              ],
              "properties":{
                "amount":{
                  "type":[
                    "null",
                    "string"
                  ]
                },
                "currencyCode":{
                  "type":[
                    "null",
                    "string"
                  ]
                }
              }
            },
            "creativeSelection":{
              "type":[
                "null",
                "string"
              ]
            },
            "costType":{
              "type":[
                "null",
                "string"
              ]
            },
            "name":{
              "type":[
                "null",
                "string"
              ]
            },
            "offsiteDeliveryEnabled":{
              "type":[
                "null",
                "boolean"
              ]
            },
            "id":{
              "type":[
                "null",
                "integer"
              ]
            },
            "audienceExpansionEnabled":{
              "type":[
                "null",
                "boolean"
              ]
            },
            "account":{
              "type":[
                "null",
                "string"
              ]
            },
            "status":{
              "type":[
                "null",
                "string"
              ]
            },
            "storyDeliveryEnabled":{
              "type":[
                "null",
                "boolean"
              ]
            },
            "pacingStrategy":{
              "type":[
                "null",
                "string"
              ]
            },
            "format":{
              "type":[
                "null",
                "string"
              ]
            },
            "objectiveType":{
              "type":[
                "null",
                "string"
              ]
            }
          }
        },
        "supportedSyncModes":[
          "full_refresh",
          "incremental"
        ],
        "sourceDefinedCursor":true,
        "defaultCursorField":[
          "lastModified"
        ],
        "sourceDefinedPrimaryKey":[
          [
            "id"
          ]
        ],
        "namespace":null
      },
      "config":{
        "syncMode":"full_refresh",
        "cursorField":[
          "lastModified"
        ],
        "destinationSyncMode":"append",
        "primaryKey":[
          [
            "id"
          ]
        ],
        "aliasName":"campaigns",
        "selected":true
      }
    },
    {
      "stream":{
        "name":"creatives",
        "jsonSchema":{
          "type":[
            "null",
            "object"
          ],
          "properties":{
            "campaign":{
              "type":[
                "null",
                "string"
              ]
            },
            "created":{
              "type":[
                "null",
                "string"
              ],
              "format":"date-time"
            },
            "lastModified":{
              "type":[
                "null",
                "string"
              ],
              "format":"date-time"
            },
            "id":{
              "type":[
                "null",
                "integer"
              ]
            },
            "reference":{
              "type":[
                "null",
                "string"
              ]
            },
            "review":{
              "type":[
                "null",
                "object"
              ],
              "properties":{
                "reviewStatus":{
                  "type":[
                    "null",
                    "string"
                  ]
                }
              }
            },
            "status":{
              "type":[
                "null",
                "string"
              ]
            },
            "type":{
              "type":[
                "null",
                "string"
              ]
            },
            "variables":{
              "type":[
                "null",
                "object"
              ],
              "properties":{
                "click_uri":{
                  "type":[
                    "null",
                    "string"
                  ]
                },
                "type":{
                  "type":[
                    "null",
                    "string"
                  ]
                },
                "values":{
                  "type":[
                    "null",
                    "array"
                  ],
                  "items":{
                    "type":[
                      "null",
                      "object"
                    ],
                    "properties":{
                      "key":{
                        "type":[
                          "null",
                          "string"
                        ]
                      },
                      "value":{
                        "type":[
                          "null",
                          "string"
                        ]
                      }
                    }
                  }
                }
              }
            },
            "version":{
              "type":[
                "null",
                "object"
              ],
              "additionalProperties":false,
              "properties":{
                "versionTag":{
                  "type":[
                    "null",
                    "string"
                  ]
                }
              }
            },
            "test":{
              "type":[
                "null",
                "boolean"
              ]
            },
            "servingStatuses":{
              "type":[
                "null",
                "array"
              ],
              "items":{
                "type":[
                  "null",
                  "string"
                ]
              }
            }
          }
        },
        "supportedSyncModes":[
          "full_refresh",
          "incremental"
        ],
        "sourceDefinedCursor":true,
        "defaultCursorField":[
          "lastModified"
        ],
        "sourceDefinedPrimaryKey":[
          [
            "id"
          ]
        ],
        "namespace":null
      },
      "config":{
        "syncMode":"full_refresh",
        "cursorField":[
          "lastModified"
        ],
        "destinationSyncMode":"append",
        "primaryKey":[
          [
            "id"
          ]
        ],
        "aliasName":"creatives",
        "selected":true
      }
    }
  ]
}`
