{{- if .Values.airbyte.external }}
apiVersion: v1
kind: Service
metadata:
  name: airbyte-server
  annotations:
    "helm.sh/hook-weight": "0"
  labels:
    app.kubernetes.io/name: airbyte-server-service
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  type: ExternalName
  externalName: {{ .Values.airbyte.serviceName }}
{{- end }}