{{- if and .Values.certManager.enabled .Values.certManager.provisionIssuer }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuerName }}
  annotations:
    "helm.sh/hook-weight": "0"
spec:
  acme:
    email: matthieu@heybutler.io
    privateKeySecretRef:
      name: {{ .Values.certManager.issuerName }}
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - selector:
          dnsZones:
            - {{ .Values.certManager.dnsZone }}
        dns01:
          route53:
            region: {{ default "us-east-2" .Values.certManager.route53.region }}
            hostedZoneID: {{ .Values.certManager.route53.hostedZoneID }}
{{- end }}