apiVersion: batch/v1
kind: Job
metadata:
  name: butler-databases-schemas-migrations-job
  labels:
    app.kubernetes.io/name: butler-databases-schemas-migrations-job
    app.kubernetes.io/component: job
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  template:
    metadata:
      name: butler-databases-schemas-migrations
    spec:
      restartPolicy: Never
      containers:
        - name: butler-databases-schemas-migrations
          image: "{{ .Values.image.repository }}/butler-victorinox:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVICES_USERS_POSTGRES_HOST
              value: {{ .Values.services.users.postgres.host | quote }}
            - name: SERVICES_USERS_POSTGRES_NAME
              value: {{ .Values.services.users.postgres.name | quote }}
            - name: SERVICES_USERS_POSTGRES_PORT
              value: "5432"
            - name: SERVICES_USERS_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-users-secrets
                  key: POSTGRES_USER
            - name: SERVICES_USERS_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-users-secrets
                  key: POSTGRES_PASSWORD
            - name: SERVICES_OCTOPUS_POSTGRES_HOST
              value: {{ .Values.services.users.postgres.host | quote }}
            - name: SERVICES_OCTOPUS_POSTGRES_NAME
              value: {{ .Values.services.octopus.postgres.name | quote }}
            - name: SERVICES_OCTOPUS_POSTGRES_PORT
              value: "5432"
            - name: SERVICES_OCTOPUS_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-octopus-secrets
                  key: POSTGRES_USER
            - name: SERVICES_OCTOPUS_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-octopus-secrets
                  key: POSTGRES_PASSWORD
            {{- range $key, $val := .Values.commonEnv }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end}}
          command: ["/butler-victorinox", "migrate", "up", "--all"]
