apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  labels:
    app.kubernetes.io/name: service-gateway
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/component: service
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  type: {{ default "ClusterIP" .Values.services.gateway.serviceType }}
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: service-gateway
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/component: service
    app.kubernetes.io/version: {{ .Chart.AppVersion }}