apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-svc-gateway
  labels:
    app.kubernetes.io/name: service-gateway
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/component: service
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: service-gateway
      app.kubernetes.io/instance: {{ .Release.Name}}
      app.kubernetes.io/component: service
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-gateway
        app.kubernetes.io/instance: {{ .Release.Name}}
        app.kubernetes.io/component: service
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
    spec:
      containers:
        - name: butler-svc-gateway
          image: "{{ .Values.image.repository }}/butler-gateway:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name}}-svc-gateway
          ports:
            - name: http
              containerPort: {{ default "5000" .Values.services.gateway.containerPort }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
