apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-svc-octopus
  labels:
    app.kubernetes.io/name: service-octopus
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/component: service
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: service-octopus
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/component: service
    app.kubernetes.io/version: {{ .Chart.AppVersion }}