apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-octopus-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.services.octopus.postgres.password }}
  POSTGRES_USER: {{ .Values.services.octopus.postgres.user }}
  {{- range $key, $val := .Values.services.octopus.config.secrets }}
  {{ $key }}: {{ $val | quote | b64enc }}
  {{- end}}

