apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-octopus-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.services.octopus.postgres.password | quote | b64enc }}
  POSTGRES_USER: {{ .Values.services.octopus.postgres.user | quote | b64enc }}
  {{- range $key, $val := .Values.services.octopus.config.secrets }}
  {{ $key }}: {{ $val | quote | b64enc }}
  {{- end}}

