{{- if .Values.services.octopus.postgres.external }}
apiVersion: v1
kind: Service
metadata:
  name: octopus-postgres
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
  labels:
    app.kubernetes.io/name: postgresql-octopus
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  type: ExternalName
  externalName: {{ .Values.services.octopus.postgres.host }}
{{- end }}