apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-svc-users
  labels:
    app.kubernetes.io/name: service-users
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/component: service
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: service-users
      app.kubernetes.io/instance: {{ .Release.Name}}
      app.kubernetes.io/component: service
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-users
        app.kubernetes.io/instance: {{ .Release.Name}}
        app.kubernetes.io/component: service
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
    spec:

      containers:
        - name: butler-svc-users
          image: "{{ .Values.image.repository }}/butler-users:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name}}-svc-users
          ports:
            - name: http
              containerPort: {{ .Values.services.users.containerPort }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: /
              port: http
