apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-svc-users
  labels:
    app.kubernetes.io/name: service-users
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/component: service
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: service-users
      app.kubernetes.io/instance: {{ .Release.Name}}
      app.kubernetes.io/component: service
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-users
        app.kubernetes.io/instance: {{ .Release.Name}}
        app.kubernetes.io/component: service
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
    spec:

      containers:
        - name: butler-svc-users
          image: "{{ .Values.image.repository }}/butler-users:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.services.users.postgres.host }}
            - name: POSTGRES_NAME
              value: {{ .Values.services.users.postgres.name }}
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-users-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-users-secrets
                  key: POSTGRES_PASSWORD
            {{- range $key, $val := .Values.commonEnv }}
            - name: $key
              value: $val
            {{- end}}
            {{- range $key, $val := .Values.services.users.config.env }}
            - name: $key
              value: $val
            {{- end}}
            {{- $releaseName := .Release.Name -}}
            {{- range $key, $val := .Values.services.users.config.secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $releaseName }}-users-secrets
                  key: {{ $key }}
            {{- end}}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          readinessProbe:
            exec:
              command: ["/grpc-health-probe", "-addr=:5000"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/grpc-health-probe", "-addr=:5000"]
            initialDelaySeconds: 10
