apiVersion: v1
kind: Service
metadata:
  name: users-server
  labels:
    app.kubernetes.io/name: service-users
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/component: service
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
      name: http
      targetPort: {{ .Values.services.users.port }}
  selector:
    app.kubernetes.io/name: service-users
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/component: service
    app.kubernetes.io/version: {{ .Chart.AppVersion }}