apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-users-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.services.users.postgres.password | b64enc }}
  POSTGRES_USER: {{ .Values.services.users.postgres.user | b64enc }}
  {{- range $key, $val := .Values.services.users.config.secrets }}
  {{ $key }}: {{ $val | quote | b64enc }}
  {{- end}}

