apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-users-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.services.users.postgres.password }}
  POSTGRES_USER: {{ .Values.services.users.postgres.user }}
  {{- range $key, $val := .Values.services.users.config.secrets }}
  {{ $key }}: {{ $val | quote | b64enc }}
  {{- end}}

