apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-users-secrets
type: Opaque
data:
  {{- range $key, $val := .Values.services.users.config.secrets }}
  {{ $key }}: {{ $val | quote | b64enc }}
  {{- end}}

