kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name}}-svc-users
  labels:
    app.kubernetes.io/name: service-users
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/component: service
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
data:
  ENVIRONMENT: {{ default "local" .Values.environment | quote }}
  LOGGER_LEVEL: "debug"
  LOGGER_ENCODING: "json"
  LOGGER_DISABLE_CALLER: "true"
  LOGGER_DISABLE_STACKTRACE: "false"
  JAEGER_HOST: {{ default "jaeger-agent:6831" .Values.jaeger.host | quote }}
  POSTGRES_HOST: {{ default "" .Values.services.users.postgres.host | quote }}
  POSTGRES_PORT: {{ default "5432" .Values.services.users.postgres.port | quote }}
  POSTGRES_NAME: {{ default "butler_users" .Values.services.users.postgres.name | quote }}
  POSTGRES_USER: {{ default "postgres" .Values.services.users.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ default "password" .Values.services.users.postgres.password | quote }}
  JWTSECRET: {{ default "superSecret" .Values.services.users.jwtSecret | quote }}
