apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name}}-svc-webapp
  labels:
    app.kubernetes.io/name: service-webapp
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/component: service
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    {{- if .Values.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.certManager.issuerName }}
    {{- end }}
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.services.webapp.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name}}-svc-webapp
                port:
                  number: 80
  {{- if .Values.certManager.enabled }}
  tls:
    - hosts:
        - {{ .Values.services.webapp.host }}
      secretName: "{{ .Values.services.webapp.host }}-cert"
  {{- end }}