apiVersion: v1
kind: Service
metadata:
  name: butler-users
  labels:
    app.kubernetes.io/name: butler-users
    app.kubernetes.io/component: service
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: butler-users
    app.kubernetes.io/component: service
    app.kubernetes.io/version: {{ .Chart.AppVersion }}