environment: local
replicaCount: 1
image:
  repository: butlerhq
  pullPolicy: IfNotPresent
  tag: "test"

jaegertracing:
  elasticsearch:
    replicaCount: 1

provisionStore:
#  elasticsearch: true

services:
  certManager:
    enabled: false
  webapp:
    containerPort: 80
    host: app.heybutler.local
  users:
    jwtSecret: superSecret
    containerPort: 5001
    postgres:
      host: butler-users-db-postgresql
      name: butler_users
      user: postgres
      password: password
  gateway:
    containerPort: 5000
    host: openapi.heybutler.local

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

elasticsearch:
  # Permit co-located instances for solitary minikube virtual machines.
  antiAffinity: "soft"

  # Shrink default JVM heap.
  esJavaOpts: "-Xmx128m -Xms128m"

  # Allocate smaller chunks of memory per pod.
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "512M"

  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 100M
