name: "Build artifacts"

on: pull_request

jobs:
  version:
    runs-on: ubuntu-latest
    name: Set release tag version
    outputs:
      version: ${{ steps.version.outputs.version_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract version from release
        id: release
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        run: |
          echo "::set-output name=version::${BRANCH_NAME#release/}"

      - name: Extract version from hotfix
        id: hotfix
        if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
        run: |
          echo "::set-output name=version::${BRANCH_NAME#hotfix/}"

      - name: Extract version from git commit sha
        id: commit
        if: ${{ !startsWith(github.event.pull_request.head.ref, 'release/') && !startsWith(github.event.pull_request.head.ref, 'hotfix/') }}
        run: |
          echo "::set-output name=version::${{ github.event.pull_request.head.sha }}"

      - name: Print version
        id: version
        run: |
          if [ "${{ steps.release.outputs.version }}" != "" ]; then
            echo "::set-output name=version_number::${{ steps.release.outputs.version }}"
          elif [ "${{ steps.hotfix.outputs.version }}" != "" ]; then
            echo "::set-output name=version_number::${{ steps.hotfix.outputs.version }}"
          else
            echo "::set-output name=version_number::${{ steps.commit.outputs.version }}"
          fi

  build-services:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test version
        env:
          NEEDS: ${{ toJson(needs) }}
        run: echo "$NEEDS"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push services
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          DOCKER_IMAGE_TAG: ${{ needs.version.outputs.version }}
          DOCKER_PUSH: true
        run: |
          DOCKER_REGISTRY="$ECR_REGISTRY/butlerhq" \
          make docker-services

  build-victorinox:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push victorinox
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          DOCKER_IMAGE_TAG: ${{ needs.version.outputs.version }}
          DOCKER_PUSH: true
        run: |
          DOCKER_REGISTRY="$ECR_REGISTRY/butlerhq" \
          make docker-victorinox

  build-webapp:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push webapp
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          DOCKER_IMAGE_TAG: ${{ needs.version.outputs.version }}
          DOCKER_PUSH: true
          APP_VERSION: ${{ needs.version.outputs.version }}
          APP_BASE_URL:  ${{ secrets.GATEWAY_PUBLIC_URL }}
        run: |
          DOCKER_REGISTRY="$ECR_REGISTRY/butlerhq" \
          make docker-webapp