name: "Draft new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release.'
        required: true

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.version }}

      # In order to make a commit, we need to initialize a user.
      # You may choose to write something less generic here if you want, it doesn't matter functionality wise.
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Bump webapp version
        run: cd webapp && yarn version --new-version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          git add *
          git commit --message "Prepare release ${{ github.event.inputs.version }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Push new release branch
        run: |
          git push origin release/${{ github.event.inputs.version }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Release ${{ github.event.inputs.version }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: release/${{ github.event.inputs.version }}
          base: master
          delete-branch: true
          title: |
            RELEASE: v${{ github.event.inputs.version }}
          body: |
            This PR was created in response to a manual trigger of the release workflow [here][1]
            This is a new release: v${{ github.event.inputs.version }}
            I've updated the changelog and bumped the versions in the manifest files in this commit: ${{ steps.make-commit.outputs.commit }}.
            Merging this PR will create a GitHub release, upload all artifacts created as part of the release build and create a new deployment.

            [1]https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          labels: |
            release
            automated pr
          draft: true