name: "Draft new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The Release Version'
        required: true

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          ref: master

      - name: Create release branch
        run: |
          echo ${{ github.ref }}
          git fetch origin develop:develop
          git reset --hard develop

      - name: Bump webapp version
        run: cd webapp && yarn version --new-version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: List file
        run: |
          ls .github/workflows
          echo ${{ github.ref }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: Release ${{ github.event.inputs.version }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: release/${{ github.event.inputs.version }}
          delete-branch: true
          title: "RELEASE: ${{ github.event.inputs.version }} 🚀"
          body: |
            This PR was created in response to a manual trigger of the release workflow [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            This is a new release: v${{ github.event.inputs.version }}
            I've updated the changelog and bumped the versions in the manifest files in this commit: ${{ steps.make-commit.outputs.commit }}.
            Merging this PR will create a GitHub release, upload all artifacts created as part of the release build and create a new deployment.
          labels: |
            release
            automated pr
          draft: false