# Default values for webapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: local

replicaCount: 1

provisionStore:
  elasticsearch: false

jaeger:
  enabled: false
  addr: "jaeger-agent:6831"
  logSpans: true

image:
  repository: butlerhq
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


certManager:
  enabled: true
  provisionIssuer: true
  issuerName: letsencrypt-prod
  dnsZone: heybutler.io
  route53:
    region: "us-east-2"
    hostedZoneID: "zoneID"

services:
  webapp:
    containerPort: 80
    host: app.heybutler.io
  users:
    jwtSecret: superSecret
    containerPort: 5001
    postgres:
      host: butler-users-db-postgresql
      name: users_db
      user: butler
      password: password
  gateway:
    containerPort: 5000
    host: api.heybutler.io

resources:
   limits:
     cpu: 200m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
