# Default values for webapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: local

replicaCount: 1

provisionStore:
  elasticsearch: false

jaeger:
  enabled: false
  addr: "jaeger-agent:6831"
  logSpans: true

image:
  repository: butlerhq
  pullPolicy: Always
  tag: ""


certManager:
  enabled: true
  provisionIssuer: true
  issuerName: letsencrypt-prod
  dnsZone: heybutler.io
  route53:
    region: "us-east-2"
    hostedZoneID: "zoneID"

commonEnv:
  ENVIRONMENT: "local"
  LOGGER_LEVEL: "debug"
  LOGGER_ENCODING: "json"
  LOGGER_DISABLE_CALLER: "true"
  LOGGER_DISABLE_STACKTRACE: "false"
  JAEGER_ADDR: "jaeger-agent:6831"
  JAEGER_DISABLED: "true"

services:
  webapp:
    serviceType: ClusterIP
    containerPort: 80
    host: app.heybutler.io

  users:
    config:
      env:
        WEBAPP_BASE_URL: "https://app.heybutler.io"
        AIRBYTE_SERVER_URL: "http://localhost:8001/api"
        AIRBYTE_DESTINATION_BUCKET_NAME: "butler-airbyte-data"
        AWS_S3_ENDPOINT: "http://localhost:9000"
        AWS_REGION: "us-east-2"
        REDIS_HOST: "redis-master.svc.local"

      secrets:
        SENDGRID_API_KEY: "sendgrid-api-key"
        JWT_SECRET: "super-secret-jwt"
        AWS_ACCESS_KEY_ID: minio-access-key-id
        AWS_ACCESS_KEY_SECRET: minio-access-key-secret

    containerPort: 5001
    postgres:
      external: false
      host: postgres
      name: octopus_db
      user: postgres
      password: password

  octopus:
    config:
      env:
        AIRBYTE_SERVER_URL: "http://localhost:8001/api"
        OAUTH_REDIRECT_URL: "https://app.heybutler.io/oauth"

      secrets:
        GOOGLE_CLIENT_ID: "abcde"
        GOOGLE_CLIENT_SECRET: "abcde"
        LINKEDIN_CLIENT_ID: "abcde"
        LINKEDIN_CLIENT_SECRET: "abcde"

    containerPort: 5002
    postgres:
      external: false
      host: postgres
      name: octopus_db
      user: postgres
      password: password


  gateway:
    serviceType: ClusterIP
    containerPort: 5000
    host: api.heybutler.io

redis:
  fullnameOverride: redis
  usePassword: false

resources:
   limits:
     cpu: 200m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
