# Default values for webapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: local

replicaCount: 1

provisionStore:
  elasticsearch: false

jaeger:
  enabled: false
  addr: "jaeger-agent:6831"
  logSpans: true

image:
  repository: butlerhq
  pullPolicy: Always
  tag: ""


certManager:
  enabled: true
  provisionIssuer: true
  issuerName: letsencrypt-prod
  dnsZone: heybutler.io
  route53:
    region: "us-east-2"
    hostedZoneID: "zoneID"

services:
  webapp:
    serviceType: ClusterIP
    containerPort: 80
    host: app.heybutler.io

  users:
    config:
      env:
        ENVIRONMENT: "local"
        LOGGER_LEVEL: "debug"
        LOGGER_ENCODING: "json"
        LOGGER_DISABLE_CALLER: "true"
        LOGGER_DISABLE_STACKTRACE: "false"
        JAEGER_ADDR: "jaeger-agent:6831"
        JAEGER_DISABLED: "true"
        WEBAPP_BASE_URL: "https://app.heybutler.io"

      secrets:
        SENDGRID_API_KEY: "sendgrid-api-key"
        JWT_SECRET: "super-secret-jwt"
        POSTGRES_HOST: "localhost"
        POSTGRES_PORT: 5432
        POSTGRES_NAME: users_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password

    containerPort: 5001
    postgres:
      external: false
      host: postgres
      name: octopus_db
      user: postgres
      password: password

  octopus:
    config:
      env:
        ENVIRONMENT: "local"
        LOGGER_LEVEL: "debug"
        LOGGER_ENCODING: "json"
        LOGGER_DISABLE_CALLER: "true"
        LOGGER_DISABLE_STACKTRACE: "false"
        JAEGER_ADDR: "jaeger-agent:6831"
        JAEGER_DISABLED: "true"
        AIRBYTE_SERVER_URL: "http://localhost:8001/api"
        OAUTH_REDIRECT_URL: "https://app.heybutler.io/oauth"

      secrets:
        GOOGLE_CLIENT_ID: "abcde"
        GOOGLE_CLIENT_SECRET: "abcde"
        LINKEDIN_CLIENT_ID: "abcde"
        LINKEDIN_CLIENT_SECRET: "abcde"
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        POSTGRES_NAME: octopus_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password

    containerPort: 5002
    postgres:
      external: false
      host: postgres
      name: octopus_db
      user: postgres
      password: password


  gateway:
    serviceType: ClusterIP
    containerPort: 5000
    host: api.heybutler.io

resources:
   limits:
     cpu: 200m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
